version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
