name: CI workflow

on: [push, pull_request]
  
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.18

    - name: Build x-delay and other tools
      run: go build -v ./...

    - name: Test x-delay codebase
      run: go test -v ./...
